### ISSUE TITLE
some errors and first time user experience

### ISSUE THREAD

**Issue by vesper8** [hazicms/generator#1]
Hi there!

I just discovered your package after you linked to it from the laravel-api-generator package.

I am still new to Laravel and some of the tools it uses but I thought I would mention what my experience went like.

First, when I tried to run composer update after adding your 3 lines to composer.json I got this error

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for hazicms/generator 1.0 -> satisfiable by hazicms/generator[v1.0].
    - hazicms/generator v1.0 requires mitulgolakiya/laravel-api-generator 1.2.* -> no matching package found.
```

That was because I had the mitulgolakiya/laravel-api-generator 1.3.\* in my composer.json. After I removed that line and ran composer update again it worked.

Then I followed all your instructions.. but I did not make any modifications to generator.php and modules.php. What would I need to change here if I'm happy with the default settings?

Anyway with default settings I tried to run your example

```
php artisan hazicms:generator Blog Post
```

My expectations from running this command is that it would generate the module and the model and all the scaffolding for views/controllers and it will add some entries to routes.php

Instead I am getting this error 

```
PHP Fatal error:  Class 'Modules\Blog\Providers\BlogServiceProvider' not found in /home/vagrant/Code/myLaravelApp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 541
```

It seems it is unable to create the folders for the modules. Those do not exist currently.

Can you tell me what I'm missing please?

Also.. P.S.. really looking forward to being able to put all the field options in a file and pass that to the generator! Any ETA on that feature?

Thanks!!

**Comment by vesper8** [comment]
I got past that error by modifying module.php like you suggest.

But now I am stumbling into two other breaking problems. I am still trying to run the command php artisan hazicms:generator Blog Post from a fresh state (ie everytime it fails, I delete the module and try again).

When prompted for the first field... I have tried to enter the following examples taken from your readme

title:text,'size' => 255
title:text,['size' => 255]
title:text
then empty for validation.. and empty again for next field

no matter what I try I always get this error

```
 [ErrorException]
  array_key_exists() expects parameter 2 to be array, null given
```

And if I try again, and this time I leave the first field empty, it progresses to create the migration and the model and then throws this error which is boggling me:

```
  [ErrorException]
  file_put_contents(/home/vagrant/myLaravelApp/app/Modules/Blog//home/vagrant/myLaravelApp/app/Http/Requests/CreatePostRequest.php): failed to open stream: No such file or directory

```

I really want to try your generator.. but I am completely lost why your examples are not working at all so far. Can you help me please? You can add me on skype too @vesper8 that would be very helpful and I can help test your package

**Comment by vesper8** [comment]
Finally got it to work.. sort of.

It turns out my config/generator.php was the wrong one.. it was the one from the laravel-api-generator package.

Once I replaced that I was able to solve the problems above. But then I had many other problems related to namespace. In the end, I had to use php artisan app:name HaziCms and I had to add HaziCms in multiple places inside the generator.php (base namespace and class namespaces).

Is it possible to use your generator without renaming the application to HaziCms?

Finally I was able to use the generator and gain access to the admin. I notice the admin links are incorrect for creating a new Blog Post (as in your example). It sends you to /admin/post but it should send you to /admin/posts/create

Also when going to /admin/posts/1 it correctly pulls the post from the post repository but the show.blade.php is currently empty

Anyway I hope you will be happy someone is using your package.. and hope you will continue to make it better.

**Comment by aitorjs** [comment]
First of all, thanks for share your experience and encourage to test the package. So happy for that! :-D

I make v1.0.1 with laravel-api-generator 1.3.  I do some examples and goes well. Use it.

The requirement of introduce field options in a file is on the roadmap but if you like, you can send a PR.

Is it possible to use the package on another namespace than HaziCms but you need to change some namespaces inside app/Modules/your_name/. Change all 'HaziCms' to the namespace that you want for your module.

The route for a model index view is /admin/your_model_plural so /admin/posts is the correct route.

The view show is empty because normally this view is public and has other layouts.

I added you to skype. Normally I'm on irc.freenode.net #laravel-es channel..

We are in contact!

**Comment by vesper8** [comment]
Thanks for adding me!

Yea for the path I meant.. if you goto the LTE Admin.. example /admin/posts and from here you click the included link to add a new post, it will send you to /admin/post which will 404. But if you manually goto /admin/posts/create then it shows the "Create post" blade.

As for renaming the app, I already tried renaming the namespace in module/generator and throughout the /app/ folder. The problem appeared to be that you have hardcoded dependencies inside the vendor composer package. In the AppBaseController.php inside the vendor package you use

```
use HaziCms\Http\Controllers\Controller;
```

Which causes issues if your base namespace isn't HaziCms

But maybe I am missing something here.

Anyway I added you back on Skype so you can reply here or there :)

Thanks!

**Comment by aitorjs** [comment]
You are right with the post link on the menu. I fix it tomorrow. Thanks!

Some namespaces are hardcoded. You named one but you have to modify more namespaces. 
Clearly those 'HaziCms' have to go on a config variable to can use the package outside of HaziCms. I fix it this tomorrow too!

**Comment by aitorjs** [comment]
Closed

**Comment by aitorjs** [comment]
v1.0.2 version fixes those problems.
